[tool.poetry]
name = "unicodedata-parser"
version = "0.1.0"
description = ""
authors = ["Koji Ishii <kojii@chromium.org>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
yapf = "^0.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
